CREATE TABLE player(
playerID CHAR(6) NOT NULL,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
CONSTRAINT PKplayer PRIMARY KEY (playerID)
);

CREATE TABLE pitcher (
ID INTEGER NOT NULL,
index_ INTEGER,
pitcherID CHAR(6) NOT NULL,
batterID CHAR(6) NOT NULL,
pitch_type CHAR(2),
game_date DATE,
release_speed DECIMAL(4,1),
release_pos_x DECIMAL(4,2),
release_pos_y DECIMAL(4,2),
release_pos_z DECIMAL(4,2),
events VARCHAR(50),
description VARCHAR(50),
zone INTEGER,
game_type CHAR(1),
stand CHAR(1),
p_throws CHAR(1),
home_team CHAR(3),
away_team CHAR(3),
type CHAR(1),
hit_location INTEGER,
bb_type VARCHAR(50),
balls INTEGER,
strikes INTEGER,
game_year INTEGER,
pfx_x DECIMAL(3,2),
pfx_z DECIMAL(3,2),
plate_x DECIMAL(3,2),
plate_z DECIMAL(3,2),
on_3b CHAR(6),
on_2b CHAR(6),
on_1b CHAR(6),
outs_when_up INTEGER,
inning INTEGER,
inning_topbot CHAR(3),
hc_x DECIMAL(5,2),
hc_y DECIMAL(5,2),
vx0 DECIMAL(11,9),
vy0 DECIMAL(11,8),
vz0 DECIMAL(11,9),
ax DECIMAL(11,9),
ay DECIMAL(11,9),
az DECIMAL(11,9),
sz_top DECIMAL(3,2),
sz_bot DECIMAL(3,2),
hit_distance_sc INTEGER,
launch_speed DECIMAL(4,1),
launch_angle INTEGER,
effective_speed DECIMAL(4,1),
release_spin_rate INTEGER,
release_extension DECIMAL(2,1),
game_pk INTEGER NOT NULL,
pitcher_1 CHAR(6) NOT NULL,
fielder_2 CHAR(6) NOT NULL,
fielder_3 CHAR(6) NOT NULL,
fielder_4 CHAR(6) NOT NULL,
fielder_5 CHAR(6) NOT NULL,
fielder_6 CHAR(6) NOT NULL,
fielder_7 CHAR(6) NOT NULL,
fielder_8 CHAR(6) NOT NULL,
fielder_9 CHAR(6) NOT NULL,
estimated_ba_using_speedangle DECIMAL(4,3),
estimated_woba_using_speedangle DECIMAL(4,3),
woba_value DECIMAL(3,2),
woba_denom INTEGER,
babip_value INTEGER,
iso_value INTEGER,
launch_speed_angle INTEGER,
at_bat_number INTEGER,
pitch_number INTEGER,
pitch_name VARCHAR(20),
home_score INTEGER,
away_score INTEGER,
bat_score INTEGER,
fld_score INTEGER,
post_away_score INTEGER,
post_home_score INTEGER,
post_bat_score INTEGER,
post_fld_score INTEGER,
if_fielding_alignment VARCHAR(20),
of_fielding_alignment VARCHAR(20),
spin_axis INTEGER,
delta_home_win_exp DECIMAL(4,3),
delta_run_exp DECIMAL(4,3),
des VARCHAR(1000),
CONSTRAINT PKpbp PRIMARY KEY (ID),
CONSTRAINT FKpitcherID FOREIGN KEY (pitcherID) REFERENCES player(playerID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
CONSTRAINT FKbatterID FOREIGN KEY (batterID) REFERENCES player(playerID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
CONSTRAINT FKpitcher_1 FOREIGN KEY (pitcher_1) REFERENCES pitcher(pitcherID),
CONSTRAINT FKfielder_2 FOREIGN KEY (fielder_2) REFERENCES pitcher(batterID),
CONSTRAINT FKfielder_3 FOREIGN KEY (fielder_3) REFERENCES pitcher(batterID),
CONSTRAINT FKfielder_4 FOREIGN KEY (fielder_4) REFERENCES pitcher(batterID),
CONSTRAINT FKfielder_5 FOREIGN KEY (fielder_5) REFERENCES pitcher(batterID),
CONSTRAINT FKfielder_6 FOREIGN KEY (fielder_6) REFERENCES pitcher(batterID),
CONSTRAINT FKfielder_7 FOREIGN KEY (fielder_7) REFERENCES pitcher(batterID),
CONSTRAINT FKfielder_8 FOREIGN KEY (fielder_8) REFERENCES pitcher(batterID),
CONSTRAINT FKfielder_9 FOREIGN KEY (fielder_9) REFERENCES pitcher(batterID)
)