---
title: "Untitled"
output: pdf_document
---

# Load Data
```{r}
kershaw = read.csv("kershaw.csv", head = T)
attach(kershaw)

table(pitch_type)
kershaw$new.zone = ifelse(plate_x >= -1 & plate_x < -0.33 & plate_z >= 3 & plate_z < 4, 1, 
                   ifelse(plate_x >= -0.33 & plate_x < 0.33 & plate_z >= 3 & plate_z < 4, 2,
                   ifelse(plate_x >= 0.33 & plate_x < 1 & plate_z >= 3 & plate_z < 4, 3, 
                   ifelse(plate_x >= -1 & plate_x < -0.33 & plate_z >= 2 & plate_z < 3, 4,
                   ifelse(plate_x >= -0.33 & plate_x < 0.33 & plate_z >= 2 & plate_z < 3, 5,
                   ifelse(plate_x >= 0.33 & plate_x < 1 & plate_z >= 2 & plate_z < 3, 6,
                   ifelse(plate_x >= -1 & plate_x < -0.33 & plate_z >= 1 & plate_z < 2, 7,
                   ifelse(plate_x >= -1 & plate_x < 0.33 & plate_z >= 1 & plate_z < 2, 8,
                   ifelse(plate_x >= 0.33 & plate_x < 1 & plate_z >= 1 & plate_z < 2, 9, 
                   ifelse(plate_x < 0 & plate_z >= 4, 10, 
                   ifelse(plate_x >= 0 & plate_z >= 4, 11, 
                   ifelse(plate_x < -1 & plate_z < 4 & plate_z > 1, 12,
                   ifelse(plate_x >= 1 & plate_z < 4 & plate_z > 1, 13,
                   ifelse(plate_x < 0 & plate_z < 1, 14, 15))))))))))))))

```


```{r}
TopStrikeZone <- 4
BotStrikeZone <- 1
LeftStrikeZone <- -1
RightStrikeZone <- 1
StrikeZone <- data.frame(
  x=c(LeftStrikeZone, LeftStrikeZone, RightStrikeZone, RightStrikeZone, LeftStrikeZone),
  y=c(BotStrikeZone, TopStrikeZone, TopStrikeZone, BotStrikeZone, BotStrikeZone))

library(ggplot2)
ggplot(kershaw, aes(plate_x,plate_z,color=new.zone))+
  geom_point()+
  geom_path(aes(x,y),data = StrikeZone,lwd=1,col="black")

round(table(kershaw$pitch_type)/nrow(kershaw)*100, 2)

```


# 
```{r}
library(plyr)
clayton = ddply(kershaw, .(game_date, batter, stand, at_bat_number), summarize, 
           event = paste(events, collapse = ","), 
           desc = paste(description, collapse = ","),
           pitch.type = paste(pitch_type, collapse = ","),
           plate.x = paste(plate_x, collapse = ","),
           plate.z = paste(plate_z, collapse = ","),
           zone = paste(new.zone, collapse = ","))

#write.csv(clayton, file = "clayton.csv")
```


```{r}
ck = read.csv("clayton.csv", head = T, na.strings=c("","NA"))
ck2 = ck[, c(1:9, 20:22, 33:35, 46:48, 59:61)]
ck2 = ck2[- grep("bunt", ck2$p1), ]
ck2 = ck2[- grep("bunt", ck2$p2), ]
ck2 = ck2[- grep("bunt", ck2$p3), ]

ck2$p1 = ifelse(ck2$p1 == "blocked_ball", "ball", 
                ifelse(ck2$p1 == "foul_tip", "swinging_strike", 
                       ifelse(ck2$p1 == "swinging_strike_blocked", "swinging_strike", ck2$p1)))
ck2$p2 = ifelse(ck2$p2 == "blocked_ball", "ball", 
                ifelse(ck2$p2 == "foul_tip", "swinging_strike", 
                       ifelse(ck2$p2 == "swinging_strike_blocked", "swinging_strike", ck2$p2)))
ck2$p3 = ifelse(ck2$p3 == "blocked_ball", "ball", 
                ifelse(ck2$p3 == "foul_tip", "swinging_strike", 
                       ifelse(ck2$p3 == "swinging_strike_blocked", "swinging_strike", ck2$p3)))
ck2$t1 = ifelse(ck2$t1 == "FT", "FF", ck2$t1)
ck2$t2 = ifelse(ck2$t2 == "FT", "FF", ck2$t2)
ck2$t3 = ifelse(ck2$t3 == "FT", "FF", ck2$t3)

ck.l = ck2[which(ck2$stand == "L"), ]
ck.r = ck2[which(ck2$stand == "R"), ]
index = sample(seq(1:nrow(ck.r)), size = nrow(ck.l))
ck.rr = ck.r[index, ]

clay = rbind(ck.l, ck.rr)

# first pitch
ggplot(clay, aes(x1,y1,color=p1))+
  geom_point()+
  facet_wrap(~stand,ncol=2)+
  geom_path(aes(x,y),data = StrikeZone,lwd=1,col="black")

round(table(clay$p1)/nrow(clay)*100, 2)

test2 = clay[which(clay$t1 == "SL"), ]
cor(clay[which(clay$t1 == "CH"),]$x1, clay[which(clay$t1 == "CH"),]$y1)

# second pitch
ggplot(clay, aes(x2,y2,color=t2))+
  geom_point()+
  facet_wrap(~stand,ncol=2)+
  geom_path(aes(x,y),data = StrikeZone,lwd=1,col="black")

round(table(clay$t2)/nrow(clay)*100, 2)

# third pitch
ggplot(clay, aes(x3,y3,color=t3))+
  geom_point()+
  facet_wrap(~stand,ncol=2)+
  geom_path(aes(x,y),data = StrikeZone,lwd=1,col="black")

round(table(clay$t3)/nrow(clay)*100, 2)


# pattern
clay$tz1 = paste(clay$t1, clay$z1)
clay$tz2 = paste(clay$t2, clay$z2)
clay$tz3 = paste(clay$t3, clay$z3)
round(table(clay$p1)/nrow(clay)*100, 2)
round(table(clay$t1, clay$z1)/nrow(clay)*100, 2)
round(table(clay$z1)/nrow(clay)*100, 2)

# first pitch (ball)
f.ball = clay[which(clay$p1 == "ball"), ]
round(table(f.ball$t1)/nrow(f.ball)*100, 2)
round(table(f.ball$t2)/nrow(f.ball)*100, 2)
round(table(f.ball$t2, f.ball$z2)/nrow(f.ball)*100, 2)
round(table(f.ball$p2)/nrow(f.ball)*100, 2)


# second pitch (ball-ball)
s.ball = f.ball[which(f.ball$p2 == "ball"), ]
round(table(s.ball$p3)/nrow(s.ball)*100, 2)
round(table(s.ball$t3, s.ball$z3)/nrow(s.ball)*100, 2)

# second pitch (ball-strike)
s.ballst = f.ball[-which(f.ball$p2 == "ball"), ]
s.ballst = na.omit(s.ballst)
round(table(s.ballst$p3)/nrow(s.ballst)*100, 2)
round(table(s.ballst$t3)/nrow(s.ballst)*100, 2)
round(table(s.ballst$t3, s.ballst$z3)/nrow(s.ballst)*100, 2)

# first pitch (strike)
f.strike = clay[which(clay$p1 == "called_strike"), ]
round(table(f.strike$t1)/nrow(f.strike)*100, 2)
round(table(f.strike$t2)/nrow(f.strike)*100, 2)
round(table(f.strike$z2)/nrow(f.strike)*100, 2)
round(table(f.strike$z2,f.strike$stand)/nrow(f.strike)*100, 2)
round(table(f.strike$p2)/nrow(f.strike)*100, 2)

# first pitch (foul)
f.foul = clay[which(clay$p1 == "foul"), ]
round(table(f.foul$t1)/nrow(f.foul)*100, 2)
round(table(f.foul$t2)/nrow(f.foul)*100, 2)
round(table(f.foul$z2)/nrow(f.foul)*100, 2)
round(table(f.foul$z2, f.foul$stand)/nrow(f.foul)*100, 2)
round(table(f.foul$p2)/nrow(f.foul)*100, 2)

# first pitch (swing strike)
f.swing = clay[which(clay$p1 == "swinging_strike"), ]
round(table(f.swing$t1)/nrow(f.swing)*100, 2)
round(table(f.swing$t2)/nrow(f.swing)*100, 2)
round(table(f.swing$z2)/nrow(f.swing)*100, 2)
round(table(f.swing$z2, f.swing$stand)/nrow(f.swing)*100, 2)
round(table(f.swing$p2)/nrow(f.swing)*100, 2)



f.strike = clay[-which(clay$p1 == "ball"), ]
round(table(f.strike$p2)/nrow(f.strike)*100, 2)
round(table(f.strike$t2)/nrow(f.strike)*100, 2)
round(table(f.strike$z2)/nrow(f.strike)*100, 2)
round(table(f.st.L$t2)/977*100, 2)
round(table(f.strike[which(f.strike$stand == "L"),]$t2)/977*100, 2)
round(table(f.strike[which(f.strike$stand == "R"),]$t2)/871*100, 2)

s.stb = f.strike[which(f.strike$p2 == "ball"), ]
s.stb = na.omit(s.stb)
round(table(s.stb$p3)/nrow(s.stb)*100, 2)
round(table(s.stb$t3)/nrow(s.stb)*100, 2)
round(table(s.stb$t3, s.stb$z3)/nrow(s.stb)*100, 2)

s.sts = f.strike[-which(f.strike$p2 == "ball"), ]
s.sts = na.omit(s.sts)
round(table(s.sts$p3)/nrow(s.sts)*100, 2)
round(table(s.sts$t3)/nrow(s.sts)*100, 2)
round(table(s.sts$t3, s.sts$z3)/nrow(s.sts)*100, 2)



hftest = ck[which(ck$z4 == c(10,11)),]
httest2 = hftest[which(hftest$z5 == 15),]


```

```{r}
s.ball2 = s.ball[which(s.ball$z3 == 4|s.ball$z3 == 1|s.ball$z3 == 7|s.ball$z3 == 12), ]
s.ball3 = s.ball[which(s.ball$z3 == 3|s.ball$z3 == 6|s.ball$z3 == 9|s.ball$z3 == 13), ]
# 144 obs / 72obs
s.ball3r = s.ball[which(s.ball3$stand == "R"), ]
s.ball2l = s.ball[which(s.ball2$stand == "L"), ]

round(table(s.ball2r$t3)/nrow(s.ball2r)*100, 2)
round(table(s.ball3r$t3)/nrow(s.ball3r)*100, 2)


s.ball4 = s.ball[which(s.ball$z3 == 2|s.ball$z3 == 5|s.ball$z3 == 8), ]
s.ball4r = s.ball[which(s.ball4$stand == "R"), ]
round(table(s.ball4r$p3)/nrow(s.ball4r)*100, 2)

```

